# Generated by Django 5.2 on 2026-06-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idGuest', models.IntegerField()),
                ('FullName', models.TextField(verbose_name='Полное имя')),
                ('Email', models.EmailField(max_length=254)),
                ('Birthday', models.DateField(verbose_name='День рождение')),
                ('GenderId', models.IntegerField()),
                ('StatusId', models.IntegerField()),
            ],
        ),
    ]
