# Generated by Django 5.2 on 2026-07-01 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gender', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('idGuest', models.IntegerField(primary_key=True, serialize=False)),
                ('FullName', models.TextField(verbose_name='Полное имя')),
                ('Email', models.EmailField(max_length=254)),
                ('Birthday', models.DateField(verbose_name='День рождение')),
                ('GenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender', verbose_name='пол')),
                ('StatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status', verbose_name='Статус')),
            ],
        ),
    ]
