# Generated by Django 5.2 on 2026-07-01 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
        ('guest', '0001_initial'),
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='id',
        ),
        migrations.AlterField(
            model_name='guest',
            name='GenderId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gender.gender', verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='StatusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='idGuest',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
