# Generated by Django 5.2 on 2026-07-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
        ('roomType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('IdRoom', models.IntegerField(primary_key=True, serialize=False)),
                ('Number', models.IntegerField(null=True)),
                ('HotelId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('RooomTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomType.roomtype')),
            ],
        ),
    ]
