# Generated by Django 5.2 on 2026-07-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('IdStatus', models.IntegerField(primary_key=True, serialize=False)),
                ('StatusName', models.TextField(max_length=200, verbose_name='Статус')),
            ],
        ),
    ]
