# Generated by Django 5.2 on 2026-07-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('IdHistory', models.IntegerField(primary_key=True, serialize=False)),
                ('CheckIn', models.DateField(null=True)),
                ('ChecklnOut', models.DateField(null=True)),
                ('Comment', models.TextField(max_length=200, null=True)),
                ('GuestId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.guest')),
                ('RoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
