# Generated by Django 5.2 on 2026-07-01 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guest', '0001_initial'),
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GuestId', models.IntegerField(null=True)),
                ('CheckIn', models.DateField(null=True)),
                ('ChecklnOut', models.DateField(null=True)),
                ('Comment', models.TextField(max_length=200, null=True)),
                ('IdHistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guest.guest')),
                ('RoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
        ),
    ]
