# Generated by Django 5.2 on 2026-07-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('IdGender', models.AutoField(primary_key=True, serialize=False)),
                ('GenderName', models.CharField(max_length=100)),
            ],
        ),
    ]
